remote_theme: pmarsceill/just-the-docs
title: VersionFile
description: VersionFile documentation
url: "https://kakara.org"
baseurl: "/versionfile/"
aux_links:
  "Kakara Home":
    - "https://kakara.org"

